// Automatically generated by generate-vocab-index.cjs
import type { VocabData } from "../../types/vocab";

export const topics = ["vocab_learning_online","vocab_other_800","vocab_play_games","vocab_shopping_online","vocab_social_media","vocab_sport","vocab_travelling"] as const;
export type Topic = typeof topics[number];

export const loadTopicData = async (topic: string): Promise<VocabData> => {
  switch (topic) {
    case "vocab_learning_online":
      return (await import("./vocab_learning_online.json")).default as VocabData;
    case "vocab_other_800":
      return (await import("./vocab_other_800.json")).default as VocabData;
    case "vocab_play_games":
      return (await import("./vocab_play_games.json")).default as VocabData;
    case "vocab_shopping_online":
      return (await import("./vocab_shopping_online.json")).default as VocabData;
    case "vocab_social_media":
      return (await import("./vocab_social_media.json")).default as VocabData;
    case "vocab_sport":
      return (await import("./vocab_sport.json")).default as VocabData;
    case "vocab_travelling":
      return (await import("./vocab_travelling.json")).default as VocabData;
    default:
      throw new Error(`Unknown topic: ${topic}`);
  }
};

export const loadAllData = async (): Promise<VocabData[]> => {
  return Promise.all(topics.map(topic => loadTopicData(topic)));
};
