const fs = require('fs');
const path = require('path');

const SOURCE_FILE = path.join(__dirname, '../src/data/english_vocab_practice.json');
const TARGET_DIR = path.join(__dirname, '../src/data/topics');
const INDEX_FILE = path.join(TARGET_DIR, 'index.ts');

if (!fs.existsSync(TARGET_DIR)) {
  fs.mkdirSync(TARGET_DIR, { recursive: true });
}

function splitVocab() {
  console.log('Reading source file...');
  const rawData = JSON.parse(fs.readFileSync(SOURCE_FILE, 'utf8'));
  const { meta, data } = rawData;

  const topicsMap = {};

  console.log('Grouping entries by topic...');
  data.forEach(item => {
    const topic = item.topic || 'other';
    if (!topicsMap[topic]) {
      topicsMap[topic] = [];
    }
    topicsMap[topic].push(item);
  });

  const topics = Object.keys(topicsMap);
  console.log(`Found topics: ${topics.join(', ')}`);

  topics.forEach(topic => {
    const filePath = path.join(TARGET_DIR, `${topic}.json`);
    const content = {
      meta: {
        ...meta,
        topic: topic
      },
      data: topicsMap[topic]
    };
    console.log(`Writing ${topic}.json (${topicsMap[topic].length} items)...`);
    fs.writeFileSync(filePath, JSON.stringify(content, null, 2));
  });

  console.log('Generating index.ts...');
  const indexContent = `// Automatically generated by split-vocab.js
import type { VocabData } from "../../types/vocab";

export const topics = ${JSON.stringify(topics)} as const;
export type Topic = typeof topics[number];

export const loadTopicData = async (topic: string): Promise<VocabData> => {
  switch (topic) {
${topics.map(t => `    case "${t}":
      return (await import("./${t}.json")).default as VocabData;`).join('\n')}
    default:
      throw new Error(\`Unknown topic: \${topic}\`);
  }
};

// For Random mode, we might want to load everything or have a list of all items
// For now, let's export a helper to load all data if needed (expensive but compatible)
export const loadAllData = async (): Promise<VocabData[]> => {
  return Promise.all(topics.map(topic => loadTopicData(topic)));
};
`;

  fs.writeFileSync(INDEX_FILE, indexContent);
  console.log('Done!');
}

try {
  splitVocab();
} catch (error) {
  console.error('Error splitting vocab:', error);
  process.exit(1);
}
